# -*- coding: utf-8 -*-
"""Netflix

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Lek7LDqCjhB9f0Vqg0s2tuqHDbsyDEK

Elpidio Rezende Terras 9°Periodo


Cristiano Lima Machado 9°Periodo
"""

import pandas as pd
import plotly.express as px
import streamlit as st
from collections import Counter


# URL do arquivo CSV no GitHub
url = 'https://raw.githubusercontent.com/ElpidioTerras/Trabalho_Netflix/main/netflix_titles.csv'

df = pd.read_csv(url)

# Imprimindo a coluna tittle e rating
#print(df[['title', 'rating']].head())

# 10 gêneros mais procurados
all_genres = df['listed_in'].str.split(',').explode().str.strip()
genre_counts = Counter(all_genres)
genre_counts_df = pd.DataFrame(genre_counts.items(), columns=['Genre', 'Count']).sort_values(by='Count', ascending=False)

# Gráfico de barras horizontal dos 10 gêneros mais procurados
fig_genre_counts = px.bar(
    genre_counts_df.head(10),
    x='Count',
    y='Genre',
    orientation='h',
    title='Top 10 Gêneros Mais Procurados',
    labels={'Count': 'Contagem', 'Genre': 'Gênero'}
)

# Apresentar o gráfico dos 10 gêneros mais procurados
st.plotly_chart(fig_genre_counts)

# Antigos (lançados antes de 2000)
old_movies = df[df['release_year'] < 2000]
old_movie_counts_by_year = old_movies.groupby('release_year').size().reset_index(name='Count')

# Gráfico de barras dos filmes antigos por ano de lançamento
fig_old_movies = px.bar(
    old_movie_counts_by_year,
    x='release_year',
    y='Count',
    title='Filmes Antigos por Ano de Lançamento',
    labels={'release_year': 'Ano de Lançamento', 'Count': 'Número de Filmes'}
)

# Apresentar o gráfico dos filmes antigos por ano de lançamento
st.plotly_chart(fig_old_movies)

# Filmes lançados a partir de 2010
recent_movies = df[df['release_year'] > 2010]
recent_movie_counts_by_year = recent_movies.groupby('release_year').size().reset_index(name='Count')

# Gráfico de barras dos filmes recentes por ano de lançamento
fig_recent_movies = px.bar(
    recent_movie_counts_by_year,
    x='release_year',
    y='Count',
    title='Filmes Recentes por Ano de Lançamento',
    labels={'release_year': 'Ano de Lançamento', 'Count': 'Número de Filmes'}
)

# Apresentar o gráfico dos filmes recentes por ano de lançamento
st.plotly_chart(fig_recent_movies)

# Filme lançado em 1925
movie_1925 = df[df['release_year'] == 1925]
#print(movie_1925)